// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ThemeConverter
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VisibilityString = "9c1e2f4b-fce1-4181-8173-31f5d9df73e5";
        public static Guid Visibility = new Guid(VisibilityString);

        public const string ThemeConverterString = "9c1e2f4b-fce1-4181-8173-31f5d9df73e4";
        public static Guid ThemeConverter = new Guid(ThemeConverterString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
    }
}